# Generated by Django 2.2 on 2021-08-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210804_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Stars',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4)),
        ),
    ]
