# Generated by Django 2.2 on 2021-08-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20210803_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rango.Category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
